### ISSUE TITLE
Flyer Distribution

### ISSUE THREAD

**Issue by chacha** [Team3128/camp#6]
Being led by Michael Chenevey. 

- [x] Update flyer for printing
- [x] Approve flyer for distribution with CCAF (Tyler)
- [x] Contact districts for letter of approval (Michael)
- [x] Contact schools for counts/distributions (Michael)
- [ ] Print flyers (Michael)
- [ ] Distribute flyers (Michael)
- [ ] Print flyers for Demonstration on March 24th (Michael)

**Comment by chacha** [comment]
@thyme4soup I'll update you when my side of things is finished.

**Comment by thyme4soup** [comment]
Dmusd is now operated only via peachjar (louies jurisdiction)
Sbusd letter of approval acquired, 20 flyers per site
Poway usd letter of approval acquired, number of flyers is site specific and varies so we need to call each site. Also use peachjar if we want to deal with that.
(Need to let louie know that peachjar requires a proof of nonprofit thingy) 
(Also how do I mark things as done)

**Comment by chacha** [comment]
@thyme4soup Click the little checkbox next to the item.

**Comment by thyme4soup** [comment]
I'm on mobile till the weekend and it won't let me

**Comment by chacha** [comment]
@thyme4soup Ok, so it looks like we just need to get the numbers and then start printing.

**Comment by thyme4soup** [comment]
I'll start contacting poway sites once I'm back

**Comment by chacha** [comment]
@thyme4soup Awesome. So on Monday we can hopefully start printing and sorting and assigning people to go distribute.

Side note: @icejannie wants to distribute flyers at RSF.

**Comment by thyme4soup** [comment]
Anything I need to do for that or does she have it

**Comment by chacha** [comment]
At some point ask her how many we need so we can print them out.

**Comment by chacha** [comment]
I sent out an email to some of the schools I found. Today I'm going to grab some people and we'll start calling schools right after school as well as start printing and sorting once we have the counts from different schools.

@thyme4soup Can you send me the approval letters? That way I can forward them to schools that I contacted via email.

**Comment by thyme4soup** [comment]
Sent to your 3128 email

**Comment by chacha** [comment]
Louie set up the Peachjar stuff, so we will be trying it out for a month to reach all of the DMUSD schools. We'll also forward it to a couple of the PUSD schools offering to put it up on the site for free.
